version: 2

models:
  - name: stg_consolidated__campaign_data
    description: This table contains performance and conversion data for Google Ads and Microsoft Ads at the campaign level.
    columns:
      - name: account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
