version: 2

models:
  - name: stg_google_ads__accounts
    description: This table contains a list of accounts with Google Ads.
    columns:
      - name: account_id
        tests:
          - unique
          - not_null
      - name: account_currency_code
        tests:
          - accepted_values:
              values: [USD]

  - name: stg_google_ads__campaign_conversions_customers
    description: This table contains conversion data for Google Ads campaigns, split by new and old customers.
    columns:
      - name: campaign_id
        tests:
          - not_null

  - name: stg_google_ads__campaign_conversions
    description: This table contains conversion data for Google Ads campaigns.
    columns:
      - name: campaign_id
        tests:
          - not_null

  - name: stg_google_ads__campaign_performance
    description: This table contains performance data for Google Ads campaigns.
    columns:
      - name: campaign_id
        tests:
          - not_null

  - name: stg_google_ads__campaigns
    description: This table contains a list of campaigns with Google Ads.
    columns:
      - name: campaign_id
        tests:
          - unique
          - not_null
