version: 2

models:
  - name: stg_google_ads__campaigns_customer_type
    description: This table contains combined performance and conversion data for Google Ads at the campaign level.
    columns:
      - name: account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
