version: 2

models:
#  - name: mrts_consolidated__accounts_backend
#    description: This table contains performance and conversion data Google Ads and Microsoft Ads combined with backend data at the account level.
# Deactivated due to OAuth problems when accessing Google sheets:
# https://github.com/fishtown-analytics/dbt/issues/1518
#    tests:
#      - unique:
#          column_name: "concat(cast (date as string), account_name)"
#    columns:
#      - name: date
#        tests:
#          - not_null
#      - name: account_name
#        tests:
#          - not_null

  - name: mrts_consolidated__campaigns_customer_type
    description: This table combines performance and conversion data for Google Ads and Microsoft Ads at the campaign level.
    tests:
      - unique:
          column_name: "concat(cast (date as string), cast (account_id as string), cast (campaign_id as string), platform_name)"
    columns:
      - name: account_id
        tests:
          - not_null
      - name: campaign_id
        tests:
          - not_null
